import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/config.ts",
    "src/automation.ts",
    "src/hosts.ts",
    "src/rpc.ts",
    "src/rpcV2.ts",
    "src/session.ts",
    "src/state.ts",
    "src/relayHost.ts",
    "src/relayServer.ts",
    "src/relay/v2/hostCarrier.ts",
    "src/relay/v2/hostRuntime.ts",
    "src/relay/v2/hostState.ts",
    "src/relay/v2/hostCommandPlane.ts",
    "src/relay/v2/resourceState.ts",
    "src/relay/v2/stateSnapshotSpool.ts",
    "src/relay/v2/token.ts",
    "src/relay/v2/issuer.ts",
    "src/relay/v2/auth.ts",
    "src/relay/v2/continuityAnchor.ts",
    "src/relay/v2/codec.ts",
    "src/relay/v2/brokerCore.ts",
    "src/relay/v2/carrierPump.ts",
    "src/relay/v2/terminalManager.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/authority.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codec.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/store.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/runtime.ts",
    "src/terminalControl/index.ts",
    "src/canonicalTerminalControlClient.ts",
    "src/larkCliBridge.ts",
    "src/feishuBridgeStorage.ts",
    "src/feishuBridge.ts",
    "src/feishuBridgeServer.ts",
  ],
  format: ["esm"],
  target: "node20",
  outDir: "dist",
  clean: true,
  splitting: false,
  banner: {
    js: 'import { createRequire } from "node:module"; const require = createRequire(import.meta.url);',
  },
  noExternal: ["ws"],
});
