import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/config.ts",
    "src/canonicalWorktreePlacement.ts",
    "src/automation.ts",
    "src/hosts.ts",
    "src/rpc.ts",
    "src/rpcV2.ts",
    "src/session.ts",
    "src/state.ts",
    "src/relayHost.ts",
    "src/relayServer.ts",
    "src/relay/v2/hostCarrier.ts",
    "src/relay/v2/hostCapabilityReadiness.ts",
    "src/relay/v2/hostRuntime.ts",
    "src/relay/v2/hostRuntimeComposition.ts",
    "src/relay/v2/hostH3ReadinessActivation.ts",
    "src/relay/v2/hostState.ts",
    "src/relay/v2/hostCommandPlane.ts",
    "src/relay/v2/canonicalBackendIdentity.ts",
    "src/relay/v2/canonicalCommandExecutorAdapter.ts",
    "src/relay/v2/canonicalTwRpcDiscovery.ts",
    "src/relay/v2/canonicalTwRpcQueryTransportAdapter.ts",
    "src/relay/v2/resourceState.ts",
    "src/relay/v2/stateSnapshotSpool.ts",
    "src/relay/v2/token.ts",
    "src/relay/v2/issuer.ts",
    "src/relay/v2/auth.ts",
    "src/relay/v2/continuityAnchor.ts",
    "src/relay/v2/externalContinuityAuthorityHttpsAdapter.ts",
    "src/relay/v2/brokerCredentialStateStore.ts",
    "src/relay/v2/brokerCredentialStateStoreNativeTarget.ts",
    "src/relay/v2/brokerCredentialStateStoreLoader.ts",
    "src/relay/v2/brokerCredentialAuthority.ts",
    "src/relay/v2/brokerCredentialHttpBoundary.ts",
    "src/relay/v2/brokerCredentialHttpIngress.ts",
    "src/relay/v2/brokerHostBootstrapHttpIngress.ts",
    "src/relay/v2/brokerCredentialNodeHttpAdapter.ts",
    "src/relay/v2/relayV2DashboardManagementProtocolV2.ts",
    "src/relay/v2/relayV2DashboardManagementAuthority.ts",
    "src/relay/v2/relayV2DashboardManagementHostCredentialAdapter.ts",
    "src/relay/v2/relayV2DashboardManagementHostConnectorAdapter.ts",
    "src/relay/v2/relayV2DashboardManagementStdio.ts",
    "src/relay/v2/codec.ts",
    "src/relay/v2/brokerCore.ts",
    "src/relay/v2/brokerProducerRegistry.ts",
    "src/relay/v2/brokerClientSocketTransport.ts",
    "src/relay/v2/brokerTransportCloseCoordinator.ts",
    "src/relay/v2/carrierPump.ts",
    "src/relay/v2/terminalManager.ts",
    "src/relay/v2/terminalDurableLineage.ts",
    "src/relay/v2/canonicalTerminalTargetResolverAdapter.ts",
    "src/relay/v2/terminalControlAuthorityAdapter.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/authority.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codec.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/store.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/runtime.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codexAppServerProducer.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codexAppServerNotificationSource.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codexAppServerProcessControllerAuthority.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codexAppServerTrustedSourceActivation.ts",
    "src/relay/extensions/agentTranscriptLifecycle/v1/codexTrustedSourceComposition.ts",
    "src/terminalControl/index.ts",
    "src/canonicalTerminalControlClient.ts",
    "src/larkCliBridge.ts",
    "src/feishuBridgeStorage.ts",
    "src/feishuBridge.ts",
    "src/feishuBridgeServer.ts",
  ],
  format: ["esm"],
  target: "node20",
  outDir: "dist",
  clean: true,
  splitting: false,
  external: [
    "./codexAppServerNotificationSource.js",
    "./codexAppServerProcessControllerAuthority.js",
  ],
  banner: {
    js: 'import { createRequire } from "node:module"; const require = createRequire(import.meta.url);',
  },
  noExternal: ["ws"],
});
