package com.tmuxworktree.mobile.core.relay.v2.state

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index

/**
 * The current run/turn identity to permanent lifecycle witness binding.
 *
 * [turnIdKey] is empty only for run scope. The mapping payload never duplicates the closed
 * lifecycle record or authority namespace; W remains the only lifecycle event evidence owner.
 */
@Entity(
    tableName = "relay_v2_agent_lifecycle_current",
    primaryKeys = [
        "profileId",
        "profileActivationGeneration",
        "principalId",
        "clientInstanceId",
        "hostId",
        "hostEpoch",
        "scopeId",
        "sessionId",
        "timelineEpoch",
        "lifecycleScope",
        "runId",
        "turnIdKey",
    ],
    foreignKeys = [
        ForeignKey(
            entity = RelayV2AgentTranscriptLifecycleStateEntity::class,
            parentColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpochKey",
            ],
            childColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
            onDelete = ForeignKey.CASCADE,
        ),
        ForeignKey(
            entity = RelayV2AgentLifecycleEventWitnessEntity::class,
            parentColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "eventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleScope",
                "runId",
                "turnIdKey",
            ],
            childColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleEventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleScope",
                "runId",
                "turnIdKey",
            ],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        Index(
            name = "index_agent_lifecycle_current_authority",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
        ),
        Index(
            name = "index_agent_lifecycle_current_event",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleEventId",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_current_seq",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeq",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_current_order",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeqOrder",
                "lifecycleEventId",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_current_witness",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleEventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleScope",
                "runId",
                "turnIdKey",
            ],
        ),
        Index(
            name = "index_agent_lifecycle_current_run_turn",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "runId",
                "lifecycleScope",
                "turnIdKey",
            ],
            unique = true,
        ),
    ],
)
internal data class RelayV2AgentLifecycleCurrentEntity(
    val profileId: String,
    val profileActivationGeneration: Long,
    val principalId: String,
    val clientInstanceId: String,
    val hostId: String,
    val hostEpoch: String,
    val scopeId: String,
    val sessionId: String,
    val timelineEpoch: String,
    val lifecycleScope: String,
    val runId: String,
    val turnIdKey: String,
    val lifecycleEventId: String,
    val agentEventSeq: String,
    val agentEventSeqOrder: String,
)

/**
 * Permanent event identity and transition evidence for one lifecycle mutation.
 *
 * There is deliberately no ordinary delete or retention limit for this table. Snapshot records
 * may lack an exact closed-event digest, so that evidence column is nullable.
 */
@Entity(
    tableName = "relay_v2_agent_lifecycle_event_witnesses",
    primaryKeys = [
        "profileId",
        "profileActivationGeneration",
        "principalId",
        "clientInstanceId",
        "hostId",
        "hostEpoch",
        "scopeId",
        "sessionId",
        "timelineEpoch",
        "eventId",
    ],
    foreignKeys = [
        ForeignKey(
            entity = RelayV2AgentTranscriptLifecycleStateEntity::class,
            parentColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpochKey",
            ],
            childColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        Index(
            name = "index_agent_lifecycle_witnesses_authority",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
        ),
        Index(
            name = "index_agent_lifecycle_witnesses_seq",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeq",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_witnesses_order",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeqOrder",
                "eventId",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_witnesses_current_binding",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "eventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleScope",
                "runId",
                "turnIdKey",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_witnesses_notification_binding",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "eventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleState",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_lifecycle_witnesses_run_turn_history",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleScope",
                "runId",
                "turnIdKey",
                "agentEventSeqOrder",
                "eventId",
            ],
        ),
    ],
)
internal data class RelayV2AgentLifecycleEventWitnessEntity(
    val profileId: String,
    val profileActivationGeneration: Long,
    val principalId: String,
    val clientInstanceId: String,
    val hostId: String,
    val hostEpoch: String,
    val scopeId: String,
    val sessionId: String,
    val timelineEpoch: String,
    val eventId: String,
    val agentEventSeq: String,
    val agentEventSeqOrder: String,
    val lifecycleScope: String,
    val runId: String,
    val turnIdKey: String,
    val sourceEpoch: String,
    val lifecycleState: String,
    val failureCode: String?,
    val failureSummary: String?,
    val occurredAtMs: Long,
    val closedEventDigest: String?,
    val witnessCanonicalJson: String,
    val witnessCanonicalUtf8Bytes: Int,
    val witnessSha256: String,
)

/** Recent, compactable exact evidence for applied non-lifecycle events. */
@Entity(
    tableName = "relay_v2_agent_recent_event_evidence",
    primaryKeys = [
        "profileId",
        "profileActivationGeneration",
        "principalId",
        "clientInstanceId",
        "hostId",
        "hostEpoch",
        "scopeId",
        "sessionId",
        "timelineEpoch",
        "agentEventSeq",
    ],
    foreignKeys = [
        ForeignKey(
            entity = RelayV2AgentTranscriptLifecycleStateEntity::class,
            parentColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpochKey",
            ],
            childColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        Index(
            name = "index_agent_recent_evidence_authority",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
        ),
        Index(
            name = "index_agent_recent_evidence_event",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "eventId",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_recent_evidence_order",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeqOrder",
                "eventId",
            ],
            unique = true,
        ),
    ],
)
internal data class RelayV2AgentRecentEventEvidenceEntity(
    val profileId: String,
    val profileActivationGeneration: Long,
    val principalId: String,
    val clientInstanceId: String,
    val hostId: String,
    val hostEpoch: String,
    val scopeId: String,
    val sessionId: String,
    val timelineEpoch: String,
    val agentEventSeq: String,
    val agentEventSeqOrder: String,
    val eventId: String,
    val closedEventDigest: String,
    val evidenceCanonicalJson: String,
    val evidenceCanonicalUtf8Bytes: Int,
    val evidenceSha256: String,
)

/**
 * Content-free durable notification ledger row produced by the reducer.
 *
 * This is not the one-shot platform claim. The adjacent notification executor continues to claim
 * against the existing claim table immediately before invoking NotificationManager. The canonical
 * payload is content-free and row-owned; it does not repeat the consumer namespace columns.
 */
@Entity(
    tableName = "relay_v2_agent_notification_ledger",
    primaryKeys = [
        "profileId",
        "profileActivationGeneration",
        "principalId",
        "clientInstanceId",
        "hostId",
        "hostEpoch",
        "scopeId",
        "sessionId",
        "timelineEpoch",
        "lifecycleEventId",
        "lifecycleState",
    ],
    foreignKeys = [
        ForeignKey(
            entity = RelayV2AgentTranscriptLifecycleStateEntity::class,
            parentColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpochKey",
            ],
            childColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
            onDelete = ForeignKey.CASCADE,
        ),
        ForeignKey(
            entity = RelayV2AgentLifecycleEventWitnessEntity::class,
            parentColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "eventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleState",
            ],
            childColumns = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleEventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleState",
            ],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        Index(
            name = "index_agent_notification_ledger_authority",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
            ],
        ),
        Index(
            name = "index_agent_notification_ledger_event",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleEventId",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_notification_ledger_seq",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeq",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_notification_ledger_witness",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "lifecycleEventId",
                "agentEventSeq",
                "agentEventSeqOrder",
                "lifecycleState",
            ],
        ),
        Index(
            name = "index_agent_notification_ledger_pending_order",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "disposition",
                "agentEventSeqOrder",
                "lifecycleEventId",
                "lifecycleState",
            ],
            unique = true,
        ),
        Index(
            name = "index_agent_notification_ledger_audit_order",
            value = [
                "profileId",
                "profileActivationGeneration",
                "principalId",
                "clientInstanceId",
                "hostId",
                "hostEpoch",
                "scopeId",
                "sessionId",
                "timelineEpoch",
                "agentEventSeqOrder",
                "lifecycleEventId",
                "lifecycleState",
            ],
        ),
    ],
)
internal data class RelayV2AgentNotificationLedgerEntity(
    val profileId: String,
    val profileActivationGeneration: Long,
    val principalId: String,
    val clientInstanceId: String,
    val hostId: String,
    val hostEpoch: String,
    val scopeId: String,
    val sessionId: String,
    val timelineEpoch: String,
    val lifecycleEventId: String,
    val lifecycleState: String,
    val agentEventSeq: String,
    val agentEventSeqOrder: String,
    val disposition: String,
    val localGeneration: String,
    val ledgerCanonicalJson: String,
    val ledgerCanonicalUtf8Bytes: Int,
    val ledgerSha256: String,
)
